#!/usr/bin/env python3
# Copyright (C) 2026 texprose contributors
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Generates defaults_gen.go from the Kotlin sources of ltex-ls-plus.
# Usage: gen_defaults.py <path-to-ltex-ls-plus-checkout> > ../defaults_gen.go

import re
import sys

REPO = sys.argv[1]
PARSING = f"{REPO}/src/main/kotlin/org/bsplines/ltexls/parsing"

SIGNATURE_REGEX = re.compile(
    r'Latex(?:Command|Environment)Signature\(\s*'
    r'"((?:[^"\\]|\\.)*)"'
    r'(?:,\s*LatexCommandSignature\.Action\.(\w+))?'
    r'(?:,\s*DummyGenerator\.getInstance\(plural = true\))?'
    r',?\s*\)',
    re.DOTALL,
)


def unescape(kotlin_string):
    return kotlin_string.replace('\\\\', '\x00').replace('\\"', '"').replace('\x00', '\\')


def go_quote(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def parse_signatures(region, default_action):
    entries = []
    for match in SIGNATURE_REGEX.finditer(region):
        prototype = unescape(match.group(1))
        action = match.group(2) or default_action
        plural = 'plural = true' in match.group(0)
        entries.append((prototype, action, plural))
    return entries


def emit_specs(name, entries):
    print(f"var {name} = []sigSpec{{")
    for prototype, action, plural in entries:
        fields = [f"prototype: {go_quote(prototype)}",
                  f"action: action{action}"]
        if plural:
            fields.append("plural: true")
        print("\t{" + ", ".join(fields) + "},")
    print("}")
    print()


def main():
    with open(f"{PARSING}/latex/LatexAnnotatedTextBuilderDefaults.kt") as f:
        defaults = f.read()
    with open(f"{PARSING}/latex/LatexFragmentizer.kt") as f:
        fragmentizer = f.read()
    with open(f"{PARSING}/bibtex/BibtexFragmentizerDefaults.kt") as f:
        bibtex = f.read()

    command_region = defaults[
        defaults.index("DEFAULT_LATEX_COMMAND_SIGNATURES"):
        defaults.index("val babelLanguageMap")
    ]
    environment_start = defaults.index("DEFAULT_LATEX_ENVIRONMENT_SIGNATURES")
    environment_region = defaults[
        environment_start:
        defaults.index("val babelLanguageMap", environment_start)
    ]

    babel_region = fragmentizer[
        fragmentizer.index("val BABEL_LANGUAGE_MAP"):
        fragmentizer.index("private val USE_PACKAGE_COMMAND_SIGNATURE ")
    ]
    babel_map = re.findall(r'map\["([^"]+)"\] = "([^"]+)"', babel_region)

    bibtex_fields = re.findall(r'map\["([^"]+)"\] = (true|false)', bibtex)

    print("// Code generated by tools/gen_defaults.py from ltex-ls-plus; DO NOT EDIT.")
    print("//")
    print("// Copyright (C) 2019-2025")
    print("// Julian Valentin, Daniel Spitzer, LTeX+ Development Community")
    print("//")
    print("// This Source Code Form is subject to the terms of the Mozilla Public")
    print("// License, v. 2.0. If a copy of the MPL was not distributed with this")
    print("// file, You can obtain one at https://mozilla.org/MPL/2.0/.")
    print()
    print("package texprose")
    print()
    emit_specs("defaultCommandSpecs", parse_signatures(command_region, "Ignore"))
    emit_specs("defaultEnvironmentSpecs", parse_signatures(environment_region, "Ignore"))

    print("var babelLanguageMap = map[string]string{")
    for key, value in babel_map:
        print(f"\t{go_quote(key)}: {go_quote(value)},")
    print("}")
    print()

    print("var defaultBibtexFields = map[string]bool{")
    for key, value in bibtex_fields:
        print(f"\t{go_quote(key)}: {value},")
    print("}")


main()
