#!/usr/bin/env python3
# Copyright (C) 2026 texprose contributors
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Generates accents_gen.go: the NFC composition table used to fold LaTeX
# accent commands (\"o, \'e, ...) to precomposed Unicode, replacing
# java.text.Normalizer used upstream. Usage: gen_accents.py > ../accents_gen.go

import string
import unicodedata

# Combining marks addressed by the accent commands in
# LatexAnnotatedTextBuilder.convertAccentCommandToUnicode.
MARKS = ["̀", "́", "̂", "̃", "̈", "̄", "̇",
         "̋", "̱", "̧", "̣", "̨", "̊", "̆",
         "̌"]

# Base letters: A-Z, a-z, dotless i (\i), dotless j (\j).
BASES = list(string.ascii_uppercase + string.ascii_lowercase) + ["ı", "ȷ"]

print("// Code generated by tools/gen_accents.py; DO NOT EDIT.")
print("//")
print("// This Source Code Form is subject to the terms of the Mozilla Public")
print("// License, v. 2.0. If a copy of the MPL was not distributed with this")
print("// file, You can obtain one at https://mozilla.org/MPL/2.0/.")
print()
print("package texprose")
print()
print("// accentComposition maps combining mark -> base letter -> NFC")
print("// precomposed character. Pairs without a precomposed form are absent")
print("// (NFC leaves them decomposed).")
print("var accentComposition = map[rune]map[rune]rune{")

for mark in MARKS:
    entries = []
    for base in BASES:
        composed = unicodedata.normalize("NFC", base + mark)
        if len(composed) == 1:
            entries.append((base, composed))
    print(f"\t0x{ord(mark):04x}: {{")
    for base, composed in entries:
        print(f"\t\t'{base}': 0x{ord(composed):04x}, // {base}{mark} -> {composed}")
    print("\t},")

print("}")
